/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as OrdineConfermatoRouteImport } from './routes/ordine-confermato'
import { Route as PagamentoPaypalRouteImport } from './routes/pagamento-paypal'
import { Route as ProdottoSlugRouteImport } from './routes/prodotto.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdineConfermatoRoute = OrdineConfermatoRouteImport.update({
  id: '/ordine-confermato',
  path: '/ordine-confermato',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoPaypalRoute = PagamentoPaypalRouteImport.update({
  id: '/pagamento-paypal',
  path: '/pagamento-paypal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdottoSlugRoute = ProdottoSlugRouteImport.update({
  id: '/prodotto/$slug',
  path: '/prodotto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contatti': typeof ContattiRoute
  '/ordine-confermato': typeof OrdineConfermatoRoute
  '/pagamento-paypal': typeof PagamentoPaypalRoute
  '/prodotto/$slug': typeof ProdottoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contatti': typeof ContattiRoute
  '/ordine-confermato': typeof OrdineConfermatoRoute
  '/pagamento-paypal': typeof PagamentoPaypalRoute
  '/prodotto/$slug': typeof ProdottoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/checkout': typeof CheckoutRoute
  '/contatti': typeof ContattiRoute
  '/ordine-confermato': typeof OrdineConfermatoRoute
  '/pagamento-paypal': typeof PagamentoPaypalRoute
  '/prodotto/$slug': typeof ProdottoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogo'
    | '/checkout'
    | '/contatti'
    | '/ordine-confermato'
    | '/pagamento-paypal'
    | '/prodotto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/checkout'
    | '/contatti'
    | '/ordine-confermato'
    | '/pagamento-paypal'
    | '/prodotto/$slug'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/checkout'
    | '/contatti'
    | '/ordine-confermato'
    | '/pagamento-paypal'
    | '/prodotto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  CheckoutRoute: typeof CheckoutRoute
  ContattiRoute: typeof ContattiRoute
  OrdineConfermatoRoute: typeof OrdineConfermatoRoute
  PagamentoPaypalRoute: typeof PagamentoPaypalRoute
  ProdottoSlugRoute: typeof ProdottoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordine-confermato': {
      id: '/ordine-confermato'
      path: '/ordine-confermato'
      fullPath: '/ordine-confermato'
      preLoaderRoute: typeof OrdineConfermatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento-paypal': {
      id: '/pagamento-paypal'
      path: '/pagamento-paypal'
      fullPath: '/pagamento-paypal'
      preLoaderRoute: typeof PagamentoPaypalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prodotto/$slug': {
      id: '/prodotto/$slug'
      path: '/prodotto/$slug'
      fullPath: '/prodotto/$slug'
      preLoaderRoute: typeof ProdottoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  CheckoutRoute: CheckoutRoute,
  ContattiRoute: ContattiRoute,
  OrdineConfermatoRoute: OrdineConfermatoRoute,
  PagamentoPaypalRoute: PagamentoPaypalRoute,
  ProdottoSlugRoute: ProdottoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
